name = "Charmey"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Charmey"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.15.0"

[[lean_lib]]
name = "Charmey"
